### ISSUE TITLE
SUPER WEIRD BUG! (Draggable example)

### ISSUE THREAD

**Issue by dmvaldman** [FamousArchives/examples#11]
Are you ready?!

```
function GenericSync(options) {
        if (arguments.length === 2){
            this._legacyPositionGetter = arguments[0];
            options = arguments[1];
        }
        else this._legacyPositionGetter = null;
         ...
```

When GenericSync is called with 2 arguments, as in Draggable.js, at the end of this code, options has the value arguments[0], and arguments = [arguments[1], arguments[1]]

@michaelobriena @ftripier @fettermania

**Comment by DrClick** [comment]
Its nothing to do with generic sync, but options is not the object, its a reference to arguments[0] so the result of arguments is as expected. Are you sure on the final value of options? I cannot reproduce that.

```
function test(options){
  console.log("options", options);

  if(arguments.length == 2){
    options = arguments[1];
    console.log("arguments", arguments);console.log("options", options);
  }
}

console.log("test with hello")
test({"Hello": "World"});

console.log("test with hello and foo")
test({"Hello": "World"}, {"Foo": "Bar"});
```

**Comment by michaelobriena** [comment]
Is this still an issue?  Draggble seems to be working with the newest code.

**Comment by dmvaldman** [comment]
This has been fixed. Closing.
