### ISSUE TITLE
For lazy folks who wants to easily view all examples

### ISSUE THREAD

**Issue by iabdulin** [FamousArchives/examples#14]
> If you want to change the current example, edit string in the require statement to point to any other file in the folder `src/examples`.
### What???

Edit,
save,
reload
for every one of **50 examples**? And then, if you want to go back, then you have to change it back, save again, and reload!
#### Here's the solution:

replace `index.html` with this _super improved version_:
https://github.com/iabdulin/examples/blob/24c02d909c2eb7e89ea09bdbc60365ff0290d575/index.html
#### What it does:

It adds ugly but useful table with links to ALL examples.
You click a link, it points to the same file as, for example `index.html?views/SequentialLayout/example.js`.

Then it requires specified example dynamically with 

``` html
<script type="text/javascript">
  require(['src/examples/' + location.search.replace('?','')]);
</script>
```

Voila!

![84697602-c134-11e3-96b6-4650b8bd6ef0-5](https://cloud.githubusercontent.com/assets/622315/2676340/907244a0-c135-11e3-9a66-e14a09bb6f2c.png)

**Comment by grigio** [comment]
+1 thanks

**Comment by thinklinux** [comment]
Nice one! Thanks.

**Comment by MrNice** [comment]
Haha, I manually changed that file 50 times.. Luckily I had a watch task running...

**Comment by chnl** [comment]
YES! thank you.

**Comment by quanghoc** [comment]
It pointed to wrong path. For example:

`src/examples/famous/core/Engine.js`

while it should be

`src/famous/core/Engine.js`

and so on...

**Comment by amitchoubey** [comment]
I used this index.html but I am getting only black screen.

![image](https://cloud.githubusercontent.com/assets/3448322/3053951/97aa0694-e1b1-11e3-8260-8eb1c87db973.png)

Please tell me if any setting is required ?
Tell step by step how can see all examples?

**Comment by michaelobriena** [comment]
@amitchoubey my guess is you need to do a "git submodule update --init --recursive" in the root directory.

I am going to be closing this as it is not a true issue.

@iabdulin, we are coming out with our forum soon so feel free to publicize your repo on there when it comes out.
