### ISSUE TITLE
Chrome Version 34.0.1847.116 - Issue on examples with non-fullscreen window.

### ISSUE THREAD

**Issue by alexandrethsilva** [FamousArchives/examples#15]
Is anybody else having incredibly slow transitions on Chrome if the window is not on fullscreen mode?

On Safari it works smoothly both ways (fullscreen and window mode), but on Chrome it runs as it should only when in fullscreen. The whole browser actually becomes completely unresponsive until the transition ends.

**Comment by DrClick** [comment]
Try making sure your terminal window is not overlapped with your browser window in any way. I found this can practically stop  animations

**Comment by alexandrethsilva** [comment]
Wow, I'm shocked. Problem solved, thanks a lot!
