### ISSUE TITLE
Explicit Z-Indexing

### ISSUE THREAD

**Issue by timjchin** [FamousArchives/examples#2]
There are quite a few examples that have surfaces that overlap, and they sit at the same exact z-depth. Since we're clearing the DOM quite often inside of FU, the surface on top is not always constant. It makes for a bad display of the example, to see the flickering as you edit content. 

This problem can be avoided if we're more careful about placing the surface that's meant to be behind, explicitly at a depth of -1, or whatever makes sense for the demo.

**Comment by michaelobriena** [comment]
Really good point.  I am going to be fixing example bugs today and will make sure I add modifiers to transform them forwards.  If you come across any particular example with this issue after today let me know I missed it.

**Comment by michaelobriena** [comment]
Fixed these
