### ISSUE TITLE
examples not running

### ISSUE THREAD

**Issue by mrqc** [FamousArchives/examples#27]
hi
i downloaded the examples as a ZIP file. I extracted them and tried to open the index.html in firefox. nothing happens. the console tells me:
Error: Script error for: famous/core/Engine
http://requirejs.org/docs/errors.html#scripterror

Error: Script error for: famous/core/Surface
http://requirejs.org/docs/errors.html#scripterror

Error: Script error for: famous/views/Scrollview
http://requirejs.org/docs/errors.html#scripterror

**Comment by iabdulin** [comment]
I think you have to run examples through a local webserver

**Comment by mrqc** [comment]
same thing if I run it via a webserver (apache in my case)

**Comment by tvararu** [comment]
The examples work fine statically. I reckon your problem is that you downloaded it as a zip file instead of using `git clone --recursive`. As such, Firefox is throwing you 404s because the files really are missing.

You can try to patch it yourself by downloading more zips, but I would just clone with recursive.

**Comment by mrqc** [comment]
ok, but when I am cloning the examples I get:

macmini:dev mrqc$ git clone git@github.com:Famous/examples.git --recursive
Cloning into 'examples'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by tvararu** [comment]
I just tested and it works if you use HTTPS. Try with the command below:

``` bash
$ git clone https://github.com/Famous/examples.git --recursive
Cloning into 'examples'...
remote: Reusing existing pack: 1639, done.
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 1646 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (1646/1646), 1.57 MiB | 280.00 KiB/s, done.
Resolving deltas: 100% (796/796), done.
Checking connectivity... done.
Submodule 'src/famous' (git@github.com:Famous/famous.git) registered for path 'src/famous'
...
```

**Comment by mrqc** [comment]
are there some pre requirements for doing this? because as you can see, it does not work for me!! i tried:

macmini:dev mrqc$ git clone https://github.com/Famous/examples.git --recursive
Cloning into 'examples'...
remote: Reusing existing pack: 1639, done.
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 1646 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (1646/1646), 1.57 MiB | 456.00 KiB/s, done.
Resolving deltas: 100% (796/796), done.
Checking connectivity... done.
Submodule 'src/famous' (git@github.com:Famous/famous.git) registered for path 'src/famous'
Cloning into 'src/famous'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:Famous/famous.git' into submodule path 'src/famous' failed

**Comment by mrqc** [comment]
Its the first checkout which takes me more than half a day!

**Comment by tvararu** [comment]
I just noticed that submodule cloning defaults through SSH. Since it's failing, I wager your Github account doesn't have a copy of your public key. Go to the [SSH Keys section](https://github.com/settings/ssh) in account management and check if `macmini` is there; if not, add it using the tutorials.

**Comment by mrqc** [comment]
this worked! I hate this setup shit

**Comment by dmvaldman** [comment]
I've changed the README, thanks for the tip!
