### ISSUE TITLE
As of 0.0.4 DragTransition doesn’t seem to work.  (not new)

### ISSUE THREAD

**Issue by fettermania** [FamousArchives/examples#3]
@mark @ftripier @michaelobriena @dmvaldman 

The element takes no visible action when clicked.

**Comment by dmvaldman** [comment]
So dragTransition may be a misnomer. It's a little different than the other transitions, in that it isn't meant to go from a value A to B, but merely to start at A and move in the direction of a given velocity, and slow down. Best application would be panning a map, or the intertial drag in scrollview.

I can make a better example for it. But we should consider maybe taking it out.

**Comment by DrClick** [comment]
I could tackle that one sounds fun

**Comment by michaelobriena** [comment]
Removed.
