### ISSUE TITLE
Black screen running any example

### ISSUE THREAD

**Issue by quanghoc** [FamousArchives/examples#33]
I used both middleman  app `bundle exec middleman server -p 10001` and `jekyll serve --watch` as I always do to run frontend backendless server. All examples came up with black screen and nothing else. I use this in Mac Chrome version.
Any idea?

**Comment by dmvaldman** [comment]
Does `main.js` require in an `example.js`?

**Comment by quanghoc** [comment]
Yes I kept that file the same and there is a `require` in `main.js`

**Comment by dmvaldman** [comment]
A black screen indicates the CSS is loading, but nothing else would indicate that there's a wrong path in the `main.js` require statement

**Comment by zgardner** [comment]
If you open Dev Tools (F12), are there any JavaScript errors in the console?

**Comment by quanghoc** [comment]
Yeah both css and js not loading. All the path in .zip file I downloaded all messed up. 

For example, with `require('/src/examples/views/Deck/example.js');`, the browser said cannot find this
`http://0.0.0.0:10001/src/famous/views/Deck.js`

That doesn't make sense at all.

Still debugging

**Comment by quanghoc** [comment]
Oh the /src/famous/ folder is empty in the zip I downloaded.

**Comment by dmvaldman** [comment]
the zip download doesn't support submodules. Please follow the instructions to download in the Readme
