### ISSUE TITLE
Transitionable example: surface doesn't show as of 0.0.4

### ISSUE THREAD

**Issue by fettermania** [FamousArchives/examples#5]
Not new since 0.0.3.  

@marklu @michaelobriena @ftripier @dmvaldman

**Comment by dmvaldman** [comment]
I can't seem to reproduce. It's working fine for me.

**Comment by marklu** [comment]
Two issues:

1.) The arbitrary maxOffset is inappropriate for the default mobile screen. Lower it to 120. Transitioning the x origin might be more appropriate in this case.
2.) The grid can potentially end up in front in a future version of famo.us. I personally think we should just remove the grid. It's extra code and doesn't serve to show anything.

One additional comment:

This example show a horrible highly inefficient way of using Modifier. Can we at least map this to a CachedMap? Or, better, if you just simply hooked up the transition to origin, the Transitionable can be used directly by the Modifier.

**Comment by michaelobriena** [comment]
I will look into rewriting this.  A lot of the examples are pulled from the header comments that used to have examples which means this code is probably very old.

**Comment by michaelobriena** [comment]
Example was rewritten
