### ISSUE TITLE
Scrollview sequence surfaces render blank when scrolling.

### ISSUE THREAD

**Issue by ReyHaynes** [FamousArchives/examples#9]
Not sure how far this goes back. Only played with 0.0.4

**Comment by michaelobriena** [comment]
Do you have a commit with this issue?

**Comment by ReyHaynes** [comment]
Nope. Just pulled this repo today. Every example works except the ones implementing scrollview.

**Comment by ftripier** [comment]
Ran into this with will, when scrolled, the group immediately deallocated
all of its surfaces and didnt bring in any of the other surfaces, but when
we updated all our submodules to develop it worked fine.

**Comment by michaelobriena** [comment]
Yup, I will update the submodules this points to.

**Comment by ReyHaynes** [comment]
Yup. That worked. Thanks guys!
